service:
  port: 4000

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - paths:
        - path: "/"
          pathType: Prefix

mysql:
  enabled: true
  auth:
    rootPassword: "admin"
    password: "password"
    database: "snippetbox"
  initdbScriptsConfigMap: "my-snippetbox-db-init"
