---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-snippetbox-db-init
data:
  # file-like keys
  init.sql: |
    -- Create a new `snippetbox` database.
    CREATE DATABASE IF NOT EXISTS snippetbox;

    -- Create a `snippets` table.
    CREATE TABLE IF NOT EXISTS snippets (
        id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
        title VARCHAR(100) NOT NULL,
        content TEXT NOT NULL,
        created DATETIME NOT NULL,
        expires DATETIME NOT NULL
    );

    -- Add an index on the created column.
    CREATE INDEX idx_snippets_created ON snippets(created);

    -- Create a new `web` user and grant it the necessary permissions on the `snippetbox` database.
    CREATE USER 'web';
    GRANT SELECT, INSERT, UPDATE, DELETE ON snippetbox.* TO 'web';

    -- Important: Make sure to swap 'pass' with a password of your own choosing.
    ALTER USER 'web' IDENTIFIED BY 'Snippets4Days';
